### PR TITLE
Annotation link fix

### LINKED ISSUE #246: Add links to annotations
Like https://github.com/sensu/web/pull/233 but for annotations. URLs and images are more commonly used to add context (annotation) and not used as an identifier (label).

## Feature Suggestion

Allow links in annotations to be clickable.

### PR DESCRIPTION
**Pull request by dabria**
## What is this change?
Properly closes #246 
Actually adds linking to annotations. Also added some QOL features, like an expandable modal will pop up if you click them, which is helpful when the values are truncated.

Screen Shot 2020-03-12 at 9 25 11 AM
Screen Shot 2020-03-12 at 9 26 20 AM
Screen Shot 2020-03-12 at 9 26 27 AM

## Why is this change necessary?
Mentioned in previous PR

## Were there any complications while making this change?
Labels and Annotations use the same component now.

## How did you verify this change?
Manually adding different types of labels and annotations to a check

### CODE REVIEW

File: src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+  DialogTitle,
+  DialogContent,
+  DialogActions,
+  Slide,
+  withStyles,
+} from "/vendor/@material-ui/core";
+import { OpenInNewIcon } from "/lib/component/icon";
+import { ModalController } from "/lib/component/controller";
+import { CodeBlock, CodeHighlight } from "/lib/component/base";
+import { KeyValueChip } from "/lib/component/partial";
```
Comment (jamesdphillips) [inline src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js]: I think this is causing the circular dep error when building.

Comment (dabria) [reply src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js]: Ah, thanks for finding that.
