### PR TITLE
Trim whitespace from username when signing in

### LINKED ISSUE #303: Strip leading/trailing whitespace from usernames in login entry.
Drove myself a little nuts when i cut and pasted a user name with a trailing space into the login box of the web-ui.

## Expected Behavior
strip leading/trailing whitespaces around usernames prior to authing

## Current Behavior
a trailing space in user name causes auth to fail.

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

Trim whitespace from username when signing in.

## Why is this change necessary?

Closes #303 

## How did you verify this change?

Manual.

### CODE REVIEW

File: src/lib/component/partial/SigninDialog/SigninForm.js [hunk 1]
```diff
@@ -20,7 +20,10 @@ const SignInForm = ({ disabled, error, onSubmit }) => {
 
   const handleSubmit = useCallback(
     ev => {
-      onSubmit({ username, password });
+      onSubmit({
+        username: username.trim(),
+        password: password.trim(),
```
Comment (dabria) [inline src/lib/component/partial/SigninDialog/SigninForm.js:25]: Does it make sense to trim whitespace from a password?

Comment (jamesdphillips) [reply src/lib/component/partial/SigninDialog/SigninForm.js]: whoops
