### PR TITLE
Validate silence's check & subscription fields

### LINKED ISSUE #85: Unexpected Error: "GraphQL error: Check cannot contain spaces or special characters"
I came across this stack trace in the UI when trying to create a new Silence. I think the error comes from the fact that I tried to use a `/` in the check name, eg: `my/check`.

## Steps to Reproduce (for bugs)

In the WebUI, create a new Silence and use a check name that contains "illegal" characters.

## Context

**Browser Stack Trace:**

at `new ApolloError` (/static/js/vendor_a994.js:89)
at `QueryManager.<anonymous>` (/static/js/vendor_a994.js:89)
at `step` (/static/js/vendor_a994.js:104)
at `Object.next` (/static/js/vendor_a994.js:104)
at `undefined` (/static/js/vendor_a994.js:104)
at `Promise.n._execute` (/static/js/vendor_a994.js:89)
at `Promise._resolveFromExecutor` (/static/js/vendor_a994.js:89)
at `new Promise` (/static/js/vendor_a994.js:89)
at `__awaiter` (/static/js/vendor_a994.js:104)
at `Object.next` (/static/js/vendor_a994.js:89)
at `notifySubscription` (/static/js/vendor_a994.js:104)
at `onNotify` (/static/js/vendor_a994.js:104)
at `SubscriptionObserver.next` (/static/js/vendor_a994.js:104)
at `notifySubscription` (/static/js/vendor_a994.js:104)
at `onNotify` (/static/js/vendor_a994.js:104)

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
  sensu/web revision: `810508c`

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

Validate silence's check & subscription fields.

## Why is this change necessary?

Closes #85 

## Do you need clarification on anything?

No.

## Were there any complications while making this change?

Javascript's RegExp implementation differs from Go's implementation; only "complicated" in that I couldn't copy and past the [patterns](https://github.com/sensu/sensu-go/blob/master/api/core/v2/validators.go#L13-L23) from the Go.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

None required.

## How did you verify this change?

Added unit tests for validators and manual.

### CODE REVIEW

File: src/lib/util/validator.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+const nameRegex = /^[\w.-]+$/g;
+const subscriptionNameRegex = /^[\w.-]+:?[\w.-]+$/g;
+
+const validateWithPattern = (name, pattern) => {
+  if (name && !name.search) {
+    return false;
+  }
+
+  return name.search(pattern) >= 0;
```
Comment (10xjs) [inline src/lib/util/validator.js]: I recommend  `regex.test(string)` instead of `string.search(regex)` to save from inadvertently calling `search` on something that happens to implement it

Comment (jamesdphillips) [reply src/lib/util/validator.js]: This was my first instinct as well, however, I ran into some weirdness in the design of the `test` method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Description

> As with exec() (or in combination with it), test() called multiple times on the same global regular expression instance will advance past the previous match.

This weird side-effect meant that multiple calls to `validate`- when the value hadn't changed- resulted different results.

```
const pattern = /^[\w-.]+$/g
const myStr = "test";

pattern.test(myStr); // true
pattern.test(myStr); // false
pattern.test(myStr); // true
pattern.test(myStr); // false
```

Comment (jamesdphillips) [reply src/lib/util/validator.js]: Then again... I don't need the global flag.

File: src/lib/util/validation.js [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { set, parsePath } from "/vendor/@10xjs/form";
 
 export const REQUIRED = "VALIDATION_REQUIRED";
 export const UNIQUE_CONSTRAINT = "VALIDATION_UNIQUE_CONSTRAINT";
+export const INVALID_SYMBOL = "INVALID_SYMBOL";
```
Comment (10xjs) [inline src/lib/util/validation.js]: I previously decided that all validation error types would be prefixed with `VALIDATION_`- although we haven't had enough use yet to prove that it's a useful pattern  🤔

File: src/lib/util/validation.js [hunk 3]
```diff
@@ -11,6 +12,10 @@ export const uniqueConstraintError = () => ({
   code: UNIQUE_CONSTRAINT,
 });
 
+export const invalidSymbolError = () => ({
+  code: INVALID_SYMBOL,
+});
+
```
Comment (10xjs) [inline src/lib/util/validation.js]: The design for these validation errors was to allow including additional data in the validation error alongside the error type. In this case we could include the offending characters and use that to render a more detailed message.

```js
export const invalidSymbolError = (characters: string) => ({
  code: INVALID_SYMBOL,
  character,
});
```
```js
const messageMap = {
  [INVALID_SYMBOL]: ({character}) => `Cannot contain ${character}`,
};
```
