### PR TITLE
Avoid exception when submitting empty SignIn form

### LINKED ISSUE #32: Sign in with unfilled login form produces an odd result
## Expected Behavior
An error is displayed, asking the user to fill in the form fields.

## Current Behavior
A stack trace flashes briefly, followed by a redirect to the login page.

## Steps to Reproduce (for bugs)
Go to the dashboard login page, log in without entering any information.

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

Avoid exception when submitting empty SignIn form

## Why is this change necessary?

Closes #32 

## Does your change need a Changelog entry?

Yup

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Too the opportunity to refactor the component to use React hooks.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

None required.

## How did you verify this change?

Manual.

### CODE REVIEW

File: src/lib/component/partial/SigninDialog/SigninForm.js [hunk 1]
```diff
@@ -14,77 +14,71 @@ const StyledDialoagActions = createStyledComponent({
...
-  static defaultProps = {
-    disabled: false,
-    error: null,
-  };
+  const handleSubmit = useCallback(
+    ev => {
+      onSubmit({ username, password });
+      ev.preventDefault();
+    },
+    [username, password],
```
Comment (10xjs) [inline src/lib/component/partial/SigninDialog/SigninForm.js]: onSubmit should be included in the deps array

Comment (jamesdphillips) [reply src/lib/component/partial/SigninDialog/SigninForm.js]: Good eye 👀
