### PR TITLE
Omit entity subscription when re-running check for proxy entity

### LINKED ISSUE #37: Ad-hoc execution for proxy checks not working / cannot match proxy entities
Ad-hoc execution of "normal" checks via the dashboard is working as expected. But the ad-hoc execution of proxy checks isn't. The message in the log is:

sensu-backend[36878]: {"check":"proxy-check-example","component":"schedulerd","level":"warning","msg":"no matching entities, check will not be published","namespace":"default","time":"2019-03-19T13:35:25+01:00"}

## Expected Behavior
Ad-hoc execution of proxy checks via the dashboard will cause that all matching entities executes the check. 

## Current Behavior
Ad-hoc execution of proxy checks via the dashboard could not match any entity. 

## Steps to Reproduce (for bugs)
1. create proxy check
2. create proxy entity
3. run ad-hoc execution via the dashboard
4. look into the log of sensu-backend

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): version 5.3.0#379593a, build 379593a8859315e746da28eedfdc8ae4907091fa, built 2019-03-07T19:00:37Z
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Debian GNU/Linux 9.8 (stretch)

### PR DESCRIPTION
**Pull request by jamesdphillips**
Closes #37

### CODE REVIEW

File: src/app/component/partial/EventDetailsContainer/EventDetailsReRunAction.js [hunk 1]
```diff
@@ -34,13 +35,19 @@ class EventDetailsReRunAction extends React.PureComponent {
   render() {
     const { children, event, client } = this.props;
 
+    // Unless this is a proxy entity target the specific entity
+    let subscriptions = [`entity:${event.entity.name}`];
```
Comment (10xjs) [inline src/app/component/partial/EventDetailsContainer/EventDetailsReRunAction.js]: This would be nicer with a const declaration and a ternary.

Comment (jamesdphillips) [reply src/app/component/partial/EventDetailsContainer/EventDetailsReRunAction.js]: image

---

In earnest though, I don't see a ton of value one way or the other. If you feel passionately about it and can find a linter rule to enforce it, I wouldn't be apposed to adding it.
